# Generated by Django 5.0.4 on 2024-05-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='supplier',
            field=models.BooleanField(default=False, verbose_name='поставщик'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
