# Generated by Django 5.0.4 on 2024-05-14 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('networks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factory',
            options={'verbose_name': 'завод', 'verbose_name_plural': 'заводы'},
        ),
        migrations.AlterModelOptions(
            name='individualentrepreneur',
            options={'verbose_name': 'индивидуальный предприниматель', 'verbose_name_plural': 'индивидуальные предприниматели'},
        ),
        migrations.AlterModelOptions(
            name='retailnetwork',
            options={'verbose_name': 'розничная сеть', 'verbose_name_plural': 'розничные сети'},
        ),
        migrations.RemoveField(
            model_name='factory',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneur',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='retailnetwork',
            name='supplier',
        ),
        migrations.AddField(
            model_name='factory',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='factory',
            name='object_id',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='object_id',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='retailnetwork',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='retailnetwork',
            name='object_id',
            field=models.PositiveIntegerField(default=2024),
        ),
    ]
