# Generated by Django 5.0.4 on 2024-05-14 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0002_alter_factory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneur',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneur',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='retailnetwork',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='retailnetwork',
            name='object_id',
        ),
        migrations.AddField(
            model_name='factory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='networks.factory', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='networks.individualentrepreneur', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='retailnetwork',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='networks.retailnetwork', verbose_name='Поставщик'),
        ),
    ]
