# Generated by Django 5.0.4 on 2024-05-16 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0003_remove_factory_content_type_remove_factory_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_by', to='networks.factory', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_by', to='networks.individualentrepreneur', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='retailnetwork',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_by', to='networks.retailnetwork', verbose_name='Поставщик'),
        ),
    ]
