# Generated by Django 5.0.4 on 2024-05-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0005_alter_factory_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='level',
            field=models.IntegerField(default=0, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='level',
            field=models.IntegerField(default=0, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='retailnetwork',
            name='level',
            field=models.IntegerField(default=0, verbose_name='Уровень'),
        ),
    ]
