# Generated by Django 5.0.4 on 2024-05-17 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0006_factory_level_individualentrepreneur_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualentrepreneur',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='retailnetwork',
            name='supplier',
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица')),
                ('house_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер дома')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Задолженность')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('level', models.IntegerField(blank=True, choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], null=True, verbose_name='Уровень')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='networks.networknode', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'звено сети',
                'verbose_name_plural': 'звенья сети',
            },
        ),
        migrations.DeleteModel(
            name='Factory',
        ),
        migrations.DeleteModel(
            name='IndividualEntrepreneur',
        ),
        migrations.DeleteModel(
            name='RetailNetwork',
        ),
    ]
