# Generated by Django 5.0.4 on 2024-05-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0008_alter_networknode_debt'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networknode',
            name='products',
            field=models.ManyToManyField(related_name='network_nodes', to='products.product', verbose_name='Продукты'),
        ),
    ]
